/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5e85fd0c8763035aac7a57d0
*
* You will get 10% discount for each one of your friends
* 
*/
// Dependencies
import React, { Component } from "react";
import { Link } from "react-router-dom";
import Utils from "../utils/utils";

// Redux
import PropTypes from "prop-types";
import { bindActionCreators } from "redux";
import { connect } from "react-redux";

// Material UI
import TextField from "@material-ui/core/TextField";
import Button from "@material-ui/core/Button";
import Select from "@material-ui/core/Select";
import MenuItem from "@material-ui/core/MenuItem";
import InputLabel from "@material-ui/core/InputLabel";
import FormControl from "@material-ui/core/FormControl";
import Chip from "@material-ui/core/Chip";
import Input from "@material-ui/core/Input";

// Custom Actions


// START IMPORT ACTIONS
import CustomerActions from "../redux/actions/CustomerActions";
import UNIQUEActions from "../redux/actions/UNIQUEActions";

// END IMPORT ACTIONS

/** APIs

* actionsCustomer.create
*	@description CRUD ACTION create
*
* actionsCustomer.update
*	@description CRUD ACTION update
*	@param ObjectId id - Id
*
* actionsCustomer.get
*	@description CRUD ACTION get
*	@param ObjectId id - Id resource
*
* actionsCustomer.list
*	@description CRUD ACTION list
*
* actionsUNIQUE.findByStaff
*	@description CRUD ACTION findByStaff
*	@param Objectid key - Id of model to search for
*

**/

class CustomerEdit extends Component {
  // Init customer
  constructor(props) {
    super(props);
    this.state = {
      customer: {}
    };
  }

  // Load data on start
  componentDidMount() {
    if (this.props.match.params.id !== "new") {
      this.props.actionsCustomer.loadCustomer(this.props.match.params.id);
      this.props.actionsUNIQUE.findByStaff(this.props.match.params.id);
    }
    
    this.props.actionsCustomer.loadCustomerList();
  }

  // Insert props customer in state
  componentWillReceiveProps(props) {
    this.setState(...this.state, {
      customer: props.customer
    });
  }

  // Save data
  save(event) {
    event.preventDefault();
    if (this.state.customer._id) {
      this.props.actionsCustomer.saveCustomer(this.state.customer).then(data => {
        this.props.history.push("/customers/");
      });
    } else {
      this.props.actionsCustomer.createCustomer(this.state.customer).then(data => {
        this.props.history.push("/customers/");
      });
    }
  }

  // Show content
  render() {
    return (
      <div>
        <h1>Customer Edit</h1>
        <form className="myForm" onSubmit={this.save.bind(this)}>

          
          <TextField
            id="Name"
            label="Name"
            value={this.state.customer.Name || ""}
            onChange={Utils.handleChange.bind(this, "customer")}
            margin="normal"
            fullWidth
          />
          
          {/* RELATIONS */}

          <h2 className="mb-20">Relations</h2>
          
          {/* Relation m:m Staff with Customer */}
          
          <FormControl fullWidth className="mb-20">
            <InputLabel htmlFor="Staff">Staff</InputLabel>
            <Select
              multiple
              value={this.state.customer.Staff || []}
              onChange={Utils.handleChangeSelect.bind(this, "customer")}
              input={<Input id="Staff" name="Staff" />}
              renderValue={selected => (
                <div>
                  {selected.map(value => (
                    <Chip key={value} label={value} />
                  ))}
                </div>
              )}
            >
              {this.props.listCustomer && this.props.listCustomer.map(item => (
                <MenuItem
                  key={item._id}
                  value={item._id}
                  style={{
                    fontWeight:
                      this.state.customer.Staff &&
                      this.state.customer.Staff.indexOf(item._id) === -1
                        ? "regular"
                        : "bold"
                  }}
                >
                  {item._id}
                </MenuItem>
              ))}
            </Select>
          </FormControl>
          
          {/* EXTERNAL RELATIONS */}
          
          {/* External relation with UNIQUE */}
          
          <h3>UNIQUE</h3>
          {(!this.props.listUNIQUE || this.props.listUNIQUE.length === 0) && 
            <div>No UNIQUE associated</div>
          }
          {this.props.listUNIQUE &&
            this.props.listUNIQUE.map((item, i) => {
              return (
                <Link to={"/uniques/" + item._id} key={item._id}>
                  {item._id}
                </Link>
              );
            })}

          
          {/* Footer */}
          <div className="footer-card">
            <Link to="/customers/">Back to list</Link>

            <Button type="submit" variant="contained" color="primary">
              Save
            </Button>
          </div>
        </form>
      </div>
    );
  }
}

// Store actions
const mapDispatchToProps = function(dispatch) {
  return { 
    actionsCustomer: bindActionCreators(CustomerActions, dispatch),
    actionsUNIQUE: bindActionCreators(UNIQUEActions, dispatch),
  };
};

// Validate types
CustomerEdit.propTypes = { 
  actionsCustomer: PropTypes.object.isRequired,
  actionsUNIQUE: PropTypes.object.isRequired,
};

// Get props from state
function mapStateToProps(state, ownProps) {
  return {
    customer: state.CustomerEditReducer.customer,
    listCustomer: state.CustomerEditReducer.listCustomer,
    listUNIQUE: state.CustomerEditReducer.listUNIQUE
  };
}

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(CustomerEdit);
